config/routes.rb
Rails.application.routes.draw do  
  resources :friends
  devise_for :users
  get 'home/about'
  root 'home#index' #root page 

  # resources :friends do
  #   collection do
  #     get :test
  #   end
  # end

  #TODO: ask why it doesn't work with get 
  post 'export_friends_data' => 'friends#export_friends_data', as: :export_friends_data

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :friends

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  helper_method :export_friends

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized to Edit this friend" if @friend.nil?
  end


  def export_friends_data
    @friends = Friend.all

    p @friends[1]
    p "Hola buenos dias"

    File.open("TESTING.txt", "w") { 
      |f| f.write "#{@friends[1].inspect}" 
    }
    send_data 'text to send', :filename => 'TESTING.txt'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
    @about_me = "Soy Jossy"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter %>
  </div>

  <div>
    <%= form.number_field :user_id,
    id: :friend_user_id, value: current_user.id,
    type: :hidden%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <thead>
      <tr>
      <td>
        <strong>First name:</strong>
        <%= friend.first_name %>
      </td>

      <td>
        <strong>Last name:</strong>
        <%= friend.last_name %>
      </td>

      <td>
        <strong>Email:</strong>
        <%= friend.email %>
      </td>

      <td>
        <strong>Phone:</strong>
        <%= friend.phone %>
      </td>

      <td>
        <strong>Twitter:</strong>
        <%= friend.twitter %>
      </td>
      <td>
      <td>
        <strong>User id:</strong>
        <%= friend.user_id %>
      </td>
      <td>
        <%= link_to "Show", friend, class: "btn btn-info"%>
      </td>
      <td>
        <%= link_to "Edit", edit_friend_path(friend), class: "btn btn-secondary"%>
      </td>
      <td>
        <%= button_to "Destroy", friend, method: :delete, data: {confirm: 'ARE YOU SURE?' }, class: "btn btn-danger"%>
      </td>
    </tr>
  </thead>
</div>

app/views/friends/_show_friend.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    <%= @friend.first_name+" "+@friend.last_name%>
  </h1>
  <p class="lead">Email: <%= @friend.email%></p>
  <p class="lead">Phone: <%= @friend.phone%></p>
  <p class="lead">Twitter: <%= @friend.twitter%></p>
</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend %> |
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/index.html.erb
<h1 style="margin-top: 2rem">
  Friends 
  <%= link_to "+", new_friend_path, class:"btn btn-secondary" %>
</h1>

<div id="friends" style="margin-bottom: 2rem">
<table class="table table-sm">
  <% @friends.each do |friend| %>
    <%= render friend %>
  <% end %>
</table>
</div>

<%= button_to  'Export data', export_friends_data_path, class:"btn btn-secondary" %>

app/views/friends/new.html.erb
<h1>Add New friend</h1>

<%= render "form", friend: @friend %>
<br>

<div>
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/show.html.erb
<%# TODO: how to call show_friend from here %>

<%= render 'show_friend' %>

<div>
  <div style="margin-top: 2rem;">
    <%= link_to "Edit this friend", edit_friend_path(@friend), class:"btn btn-secondary" %>
    <%= link_to "Back to friends", friends_path, class:"btn btn-secondary" %>
  <div>
  <div style="margin-top: 2rem;">
    <%= button_to "Destroy this friend", @friend, method: :delete, class: "btn btn-danger"%>
  </div>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Friend App', root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" 
    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" 
    aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to "Friends", friends_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
            <%= link_to "New Friend", new_friend_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
            <%= link_to "About Us", home_about_path, class:"nav-link"%>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
              <%= link_to  "Sign out", destroy_user_session_path, method: :delete, class:"nav-link"%>
          </li>
          <li class="nav-item">
              <%= link_to "Edit profile", edit_user_registration_path, class:"nav-link"%>
          </li>
        <% else %>
          <li class="nav-item">
              <%= link_to "Sign up", new_user_registration_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
              <%= link_to "Sign in", user_session_path, class:"nav-link"%>
          </li>
        <% end %>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About us....</h1>

<p>
    <%= @about_me%>
</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Hello world :D!</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-info" role="alert">
    <%= notice %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
    crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <title>Friends app</title>
  </head>
  <body>
    <%= render 'home/header' %>
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>
    
    <div class="container">
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" 
    crossorigin="anonymous"></script>

    </body>
</html>